type: rsna_1d
csv_path: '/projects/eclarson/stems/STEMC/EHR/INSPECT/RSNA/train_with_split.csv'
sample_frac: 1.0
dicom_dir:  /projects/eclarson/stems/STEMC/EHR/INSPECT/RSNA/train
target:  'pe_present_on_image'
contextualize_slice: False # To test 
sample_strategy: fix
num_slices: 150
feature_size: 768
weighted_sample: true
batch_size: 32
hdf5_path: null
hdf5_path: /projects/eclarson/stems/STEMC/EHR/INSPECT/RSNA/rsna_features/features.hdf5

pretrain_args:
  model_type: resnetv2_101_ct
  input_size: 256
  channel_type: window
