n_gpus: 1
get_features: true
stage: extract
output_dir: /projects/eclarson/stems/STEMC/EHR/INSPECT/IMAGE/inpsect/inspectamultimodaldatasetforpulmonaryembolismdiagnosisandprog-3/full/pre_features
test_split: all

exp:
  base_dir:  /projects/eclarson/stems/STEMC/EHR/INSPECT/IMAGE/inpsect/exp
  name: all # test

trainer:
  weights_summary: top
  seed: 6
  val_check_interval: 1.0
  limit_val_batches: 1.0
  resume_from_checkpoint: null
  precision: 32  # set to 16 for O1 mixed precision, 32 for O0 full precision
  max_steps: 100_000
  gradient_clip_val: 0
  num_workers: 16
  max_epochs: 1

defaults:
  - dataset: stanford_16_22
  - model: resnetv2_ct # dinov2
